"""Regenerate the checked-in static diagrams with Graphviz.

Run from the repository: uv run python scripts/render_diagrams.py
Use --check to compare without writing, or --png-dir /tmp/diagram-review
to additionally render inspection images outside the repository.
The hand-authored hero SVGs are not generated by Graphviz.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "docs" / "assets"
SVG_NS = "http://www.w3.org/2000/svg"
ET.register_namespace("", SVG_NS)


def static_svg(body: bytes) -> bytes:
    """Remove Graphviz's external DTD and retain only passive SVG primitives."""
    source = body.decode("utf-8")
    source = re.sub(r"<!DOCTYPE[^>]*>", "", source, flags=re.DOTALL)
    if "<!ENTITY" in source.upper() or "<!DOCTYPE" in source.upper():
        raise ValueError("Unexpected XML declaration")
    root = ET.fromstring(source)
    allowed = {"svg", "g", "title", "desc", "polygon", "polyline", "path", "ellipse", "text"}
    for element in root.iter():
        if element.tag.removeprefix("{" + SVG_NS + "}") not in allowed:
            raise ValueError("Unexpected SVG element")
        for name, value in element.attrib.items():
            local = name.rsplit("}", 1)[-1].lower()
            if local.startswith("on") or local in {"href", "style"} or "url(" in value.lower():
                raise ValueError("Active or referenced SVG content")
    root.set("role", "img")
    root.set("preserveAspectRatio", "xMidYMid meet")
    for dimension in ("width", "height"):
        root.set(dimension, root.get(dimension, "").replace("pt", "px"))
    ET.indent(root, space="  ")
    return ET.tostring(root, encoding="utf-8", xml_declaration=True) + b"\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check SVGs without writing them")
    parser.add_argument("--png-dir", type=Path, help="Optional external directory for visual QA")
    args = parser.parse_args()
    dot = shutil.which("dot")
    if not dot:
        parser.error("Graphviz dot is required; install Graphviz and add it to PATH")
    if args.png_dir:
        destination = args.png_dir.expanduser().resolve()
        if destination == ROOT or ROOT in destination.parents:
            parser.error("PNG inspection files must be outside the public repository")
        destination.mkdir(parents=True, exist_ok=True)
    changed = []
    sources = sorted(ASSETS.glob("*.dot"))
    if not sources:
        parser.error("No DOT sources found")
    for source in sources:
        output = static_svg(subprocess.check_output([dot, "-Tsvg", str(source)]))
        target = source.with_suffix(".svg")
        if args.check:
            if not target.is_file() or target.read_bytes() != output:
                changed.append(target.name)
        else:
            target.write_bytes(output)
        if args.png_dir:
            subprocess.run(
                [
                    dot,
                    "-Tpng",
                    "-Gdpi=120",
                    str(source),
                    "-o",
                    str(destination / (source.stem + ".png")),
                ],
                check=True,
            )
    if changed:
        print("Diagrams need regeneration: " + ", ".join(changed), file=sys.stderr)
        return 1
    print(f"{len(sources)} diagrams {'checked' if args.check else 'rendered'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
